// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegisterServiceRpcClient is the client API for RegisterServiceRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterServiceRpcClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registerServiceRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterServiceRpcClient(cc grpc.ClientConnInterface) RegisterServiceRpcClient {
	return &registerServiceRpcClient{cc}
}

func (c *registerServiceRpcClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/authV1.RegisterServiceRpc/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServiceRpcServer is the server API for RegisterServiceRpc service.
// All implementations should embed UnimplementedRegisterServiceRpcServer
// for forward compatibility
type RegisterServiceRpcServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedRegisterServiceRpcServer should be embedded to have forward compatible implementations.
type UnimplementedRegisterServiceRpcServer struct {
}

func (UnimplementedRegisterServiceRpcServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

// UnsafeRegisterServiceRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterServiceRpcServer will
// result in compilation errors.
type UnsafeRegisterServiceRpcServer interface {
	mustEmbedUnimplementedRegisterServiceRpcServer()
}

func RegisterRegisterServiceRpcServer(s grpc.ServiceRegistrar, srv RegisterServiceRpcServer) {
	s.RegisterService(&RegisterServiceRpc_ServiceDesc, srv)
}

func _RegisterServiceRpc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServiceRpcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authV1.RegisterServiceRpc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServiceRpcServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterServiceRpc_ServiceDesc is the grpc.ServiceDesc for RegisterServiceRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterServiceRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authV1.RegisterServiceRpc",
	HandlerType: (*RegisterServiceRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegisterServiceRpc_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth_service.proto",
}
